### ISSUE TITLE
Should flipping flip the offsets too?

### ISSUE THREAD

**Issue by dandv** [HubSpot/tether#106]
In this configuration, what should happen if the tether is flipped?

```js
  targetAttachment: 'bottom right',
  targetOffset: '16px 0',
  constraints: [{
    to: 'window',
    attachment: 'together',
  }]
```

Here's a [CodePen demonstrating the issue](http://codepen.io/dandv/pen/zGJNYY). I would expect the vertical offset to flip as well, but instead it remains constant:

![flip should flip the offsets too](https://cloud.githubusercontent.com/assets/33569/8801505/216f9332-2f70-11e5-8ffe-b9edff4db623.gif)

Flipping the offset would be useful if the offset is used to allow for an arrow - the arrow will be flipped, and it needs the space provided by the offset:

![flip should flip the offsets too - use case](https://cloud.githubusercontent.com/assets/33569/8801528/4b2f5a68-2f70-11e5-9e5d-f4ebe46ba961.gif)

**Comment by adamschwartz** [comment]
:+1:

**Comment by woble** [comment]
I agree that tether should be handle the flipping of the offset values when the tethered object flips.

Current solution is to avoid using tether offset and use CSS instead.

```less
// LESSCSS
@element-offset: 10px;

.element {    
    &.tether-target-attached-top {
        &.tether-element-attached-bottom {
            margin-top: -@element-offset;
        }
    }

    &.tether-target-attached-bottom {
        &.tether-element-attached-top {
            margin-top: @element-offset;
        }
    }
}
```
